name: JoanaBlass
favicon: null
layout_spectrum: 0.00951
typography_spectrum: 0.25899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e1a19'
    - '#685557'
    - '#c2c6c7'
    - '#fbe1bc'
    - '#ffbf84'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
