name: JoanaBlass
favicon: null
layout_spectrum: 0.6516663928050548
typography_spectrum: 0.9916230007074773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.107395030092448
  lightness: 0.6387657239101827
  saturation: 0.1540574859827757
  rhythmicContrast: 0.18372012372128665
purpose: []
